/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void testAdd1() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.add(1, 2), 3);
    }

    @Test
    public void testAdd2() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.add(0, 5), 5);
    }

    @Test
    public void testAdd3() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.add(1, 0), 2);
    }
}
